### ISSUE TITLE
Upload to the chrome web store

### ISSUE THREAD

**Issue by jgibo** [andresusanto/i-dont-have-time-for-bamboo#3]
Hi @andresusanto, can we upload this to the chrome web store? For some reason it keeps getting automatically uninstalled out of my extensions. Not sure whether it's something to do with the company's GSuite policies or not, but maybe if it wasn't _sideloaded_ it might not get nuked :)

I'm happy to manage the store listing if you want to add me as a maintainer to the repo.

**Comment by andresusanto** [comment]
Hi @jgibo, sounds good! Thanks for volunteering, I wanted to upload this to chrome ext store for a long time, but I haven't got the time to read the docs on how to do it 😂 I've invited you to be a maintainer of the repo. Thanks!!
